FROM ruby:2.7.0-alpine

ENV APP_HOME /myapp

WORKDIR $APP_HOME

COPY Gemfile $APP_HOME
COPY Gemfile.lock $APP_HOME

RUN set -x && \
    gem install bundler && \
    bundle install

COPY . $APP_HOME

EXPOSE 4567
CMD ["bundle", "exec", "ruby", "main.rb", "-o", "0.0.0.0"]
